# Generated by Django 4.0.4 on 2024-09-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'row', 'seat')},
        ),
    ]
