# Generated by Django 4.0.4 on 2024-10-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_alter_order_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
