# Generated by Django 4.2.9 on 2024-10-07 19:35

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_route_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.crew_image_file_path),
        ),
        migrations.AlterField(
            model_name='flight',
            name='crews',
            field=models.ManyToManyField(blank=True, related_name='flights', to='airport.crew'),
        ),
    ]
